#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ID="${DIR}/../.project-id"

if [[ ! -f $PROJECT_ID ]]; then
  echo "no project"
  exit 1
fi 

TF_VAR_project=$(cat $PROJECT_ID) terraform destroy --force
rm -rf $PROJECT_ID